import { ITile, IDndTile } from './types/types';

export const gridUnit = 100;
export const gridCols = 8;

export const dndInitialTiles: IDndTile[] = [
  {
    id: '1',
    colStart: 1,
    rowStart: 1,
    colSpan: 3,
    rowSpan: 2,
    type: 'socialMedia',
    title: 'Instagram Profile',
    link: 'https://www.instagram.com/mary_kucher',
    socialMediaType: 'instagram',
  },
  {
    id: '6',
    colStart: 4,
    rowStart: 1,
    colSpan: 3,
    rowSpan: 2,
    type: 'socialMedia',
    title: 'My Travel Vlog',
    link: 'https://www.youtube.com/watch?v=abc123',
    socialMediaType: 'youtube',
  },
  {
    id: '3',
    colStart: 7,
    rowStart: 1,
    colSpan: 3,
    rowSpan: 2,
    type: 'add-image',
    title: 'Add an Image',
  },
  {
    id: '4',
    colStart: 10,
    rowStart: 1,
    colSpan: 3,
    rowSpan: 2,
    type: 'empty',
    title: 'Empty Slot',
  },
  {
    id: '5',
    colStart: 1,
    rowStart: 3,
    colSpan: 3,
    rowSpan: 2,
    type: 'empty',
    title: 'Empty Slot',
  },
  {
    id: '2',
    colStart: 4,
    rowStart: 3,
    colSpan: 3,
    rowSpan: 2,
    type: 'add-text',
    title: 'Share Your Thoughts',
  },
];

export const initialTiles: ITile[] = [
  {
    i: '1',
    x: 0,
    y: 0,
    w: 2,
    h: 2,
    type: 'socialMedia',
    title: 'Instagram Profile',
    link: 'https://www.instagram.com/purr.in.ink?igsh=OWJieWNvbnkzeWlp',
    socialMediaType: 'instagram',
  },
  {
    i: '2',
    x: 2,
    y: 0,
    w: 2,
    h: 2,
    type: 'add-text',
    title: 'Share Your Thoughts',
  },
  {
    i: '3',
    x: 4,
    y: 0,
    w: 2,
    h: 2,
    type: 'add-image',
    title: 'Add an Image',
  },
  {
    i: '4',
    x: 0,
    y: 2,
    w: 2,
    h: 2,
    type: 'empty',
    title: 'Empty Slot',
  },
  {
    i: '5',
    x: 2,
    y: 2,
    w: 2,
    h: 2,
    type: 'empty',
    title: 'Empty Slot',
  },
  {
    i: '6',
    x: 2,
    y: 2,
    w: 2,
    h: 2,
    type: 'socialMedia',
    title: 'My Travel Vlog',
    link: 'https://www.youtube.com/watch?v=abc123',
    socialMediaType: 'youtube',
  },
];
